### ISSUE TITLE
Method Powell

### ISSUE THREAD

**Issue by velkyvont** [florafauna/optimParallel-python#11]
Hi. I'm trying to speed up the calculation of minimizing a function for which it's not possible to do a derivation, so I'm using method='Powell' which gives me relatively good results (the best of all the scipy.optimize.minimize methods). I've sped the code up using jit, but I'd like to speed it up even more. Would it be possible to rewrite your code to use method Powell?

**Comment by florafauna** [comment]
If the Powell method does multiple evaluations of the target function at each step, yes.
