### ISSUE TITLE
Python 3.11/Multiple initial guesses

### ISSUE THREAD

**Issue by JacobWren** [florafauna/optimParallel-python#12]
Hi,

1) Do you support Python 3.11?

2) My objective is not so nice (i.e., non-convex), so I want to try a handful of x0’s. Would you consider “extending” the parallelization to multiple initial guesses (my solver is not thread-safe)?

Thanks,
Jake

**Comment by florafauna** [comment]
1. yes, let me know if you run into issues.
2. I don't plan to implement this extension. I will review and maybe merge PRs.
