### ISSUE TITLE
Broken process pool running in Jypter lab on Mac and Windows

### ISSUE THREAD

**Issue by Benj-Ward** [florafauna/optimParallel-python#19]
When running your notebooks or trying to use my own function in Jypter lab for Mac or Windows, I get a similar error (linked below. Not sure exactly what the cause is, so I would appreciate advisement. Sorry for the format, it was a real pain trying to get the error message into a code or quote format.

Process SpawnProcess-5:
Process SpawnProcess-6:
Process SpawnProcess-4:
Traceback (most recent call last):
  File "/Users/wardbm1/anaconda3/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/Users/wardbm1/anaconda3/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/wardbm1/anaconda3/lib/python3.11/concurrent/futures/process.py", line 244, in _process_worker
    call_item = call_queue.get(block=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wardbm1/anaconda3/lib/python3.11/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Can't get attribute 'f' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/wardbm1/anaconda3/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/wardbm1/anaconda3/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/wardbm1/anaconda3/lib/python3.11/concurrent/futures/process.py", line 244, in _process_worker
    call_item = call_queue.get(block=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wardbm1/anaconda3/lib/python3.11/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Can't get attribute 'f' on <module '__main__' (built-in)>
  File "/Users/wardbm1/anaconda3/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/wardbm1/anaconda3/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/wardbm1/anaconda3/lib/python3.11/concurrent/futures/process.py", line 244, in _process_worker
    call_item = call_queue.get(block=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wardbm1/anaconda3/lib/python3.11/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Can't get attribute 'f' on <module '__main__' (built-in)>
---------------------------------------------------------------------------

BrokenProcessPool`                         Traceback (most recent call last)

Cell In[2], line 48
     40     print(
     41         "Time parallel {:2.2}\nTime standard {:2.2} ".format(
     42             o1_end - o1_start, o2_end - o2_start
     43         )
     44     )
     47 if __name__ == "__main__":
---> 48     main()

Cell In[2], line 21, in main()
     17 x0 = np.array([10, 20])
     19 # minimize with parallel evaluation of 'fun'
     20 # and its approximate gradient
---> 21 o1 = minimize_parallel(fun=f, x0=x0, args=0.5, parallel={"loginfo": True})
     22 print(o1)
     24 # test against scipy.optimize.minimize(method='L-BFGS-B')

File ~/anaconda3/lib/python3.11/site-packages/optimparallel.py:410, in minimize_parallel(fun, x0, args, jac, bounds, tol, options, callback, parallel)
    398 with parallel_used.get("executor") as executor:
    399     fun_jac = EvalParallel(
    400         fun=fun,
    401         jac=jac,
   (...)
    408         n=n,
    409     )
--> 410     out = minimize(
    411         fun=fun_jac.fun,
    412         x0=x0,
    413         jac=fun_jac.jac,
    414         method="L-BFGS-B",
    415         bounds=bounds,
    416         callback=callback,
    417         options=options_used,
    418     )
    420 if parallel_used.get("loginfo"):
    421     out.loginfo = {
    422         k: (
    423             lambda x: np.array(x)
   (...)
    427         for k, v in fun_jac.info.items()
    428     }

File ~/anaconda3/lib/python3.11/site-packages/scipy/optimize/_minimize.py:710, in minimize(fun, x0, args, method, jac, hess, hessp, bounds, constraints, tol, callback, options)
    707     res = _minimize_newtoncg(fun, x0, args, jac, hess, hessp, callback,
    708                              **options)
    709 elif meth == 'l-bfgs-b':
--> 710     res = _minimize_lbfgsb(fun, x0, args, jac, bounds,
    711                            callback=callback, **options)
    712 elif meth == 'tnc':
    713     res = _minimize_tnc(fun, x0, args, jac, bounds, callback=callback,
    714                         **options)

File ~/anaconda3/lib/python3.11/site-packages/scipy/optimize/_lbfgsb_py.py:307, in _minimize_lbfgsb(fun, x0, args, jac, bounds, disp, maxcor, ftol, gtol, eps, maxfun, maxiter, iprint, callback, maxls, finite_diff_rel_step, **unknown_options)
    304     else:
    305         iprint = disp
--> 307 sf = _prepare_scalar_function(fun, x0, jac=jac, args=args, epsilon=eps,
    308                               bounds=new_bounds,
    309                               finite_diff_rel_step=finite_diff_rel_step)
    311 func_and_grad = sf.fun_and_grad
    313 fortran_int = _lbfgsb.types.intvar.dtype

File ~/anaconda3/lib/python3.11/site-packages/scipy/optimize/_optimize.py:383, in _prepare_scalar_function(fun, x0, jac, args, bounds, epsilon, finite_diff_rel_step, hess)
    379     bounds = (-np.inf, np.inf)
    381 # ScalarFunction caches. Reuse of fun(x) during grad
    382 # calculation reduces overall function evaluations.
--> 383 sf = ScalarFunction(fun, x0, args, grad, hess,
    384                     finite_diff_rel_step, bounds, epsilon=epsilon)
    386 return sf

File ~/anaconda3/lib/python3.11/site-packages/scipy/optimize/_differentiable_functions.py:158, in ScalarFunction.__init__(self, fun, x0, args, grad, hess, finite_diff_rel_step, finite_diff_bounds, epsilon)
    155     self.f = fun_wrapped(self.x)
    157 self._update_fun_impl = update_fun
--> 158 self._update_fun()
    160 # Gradient evaluation
    161 if callable(grad):

File ~/anaconda3/lib/python3.11/site-packages/scipy/optimize/_differentiable_functions.py:251, in ScalarFunction._update_fun(self)
    249 def _update_fun(self):
    250     if not self.f_updated:
--> 251         self._update_fun_impl()
    252         self.f_updated = True

File ~/anaconda3/lib/python3.11/site-packages/scipy/optimize/_differentiable_functions.py:155, in ScalarFunction.__init__.<locals>.update_fun()
    154 def update_fun():
--> 155     self.f = fun_wrapped(self.x)

File ~/anaconda3/lib/python3.11/site-packages/scipy/optimize/_differentiable_functions.py:137, in ScalarFunction.__init__.<locals>.fun_wrapped(x)
    133 self.nfev += 1
    134 # Send a copy because the user may overwrite it.
    135 # Overwriting results in undefined behaviour because
    136 # fun(self.x) will change self.x, with the two no longer linked.
--> 137 fx = fun(np.copy(x), *args)
    138 # Make sure the function returns a true scalar
    139 if not np.isscalar(fx):

File ~/anaconda3/lib/python3.11/site-packages/optimparallel.py:191, in EvalParallel.fun(self, x)
    190 def fun(self, x: ArrayLike):
--> 191     self.eval_parallel(x=x)
    192     if self.verbose:
    193         print("fun(" + str(x) + ") = " + str(self.fun_val))

File ~/anaconda3/lib/python3.11/site-packages/optimparallel.py:151, in EvalParallel.eval_parallel(self, x)
    142     ftmp = self._eval_approx
    144 ret = self.executor.map(
    145     ftmp,
    146     eps_at,
   (...)
    149     itertools.repeat(self.eps),
    150 )
--> 151 ret = np.array(list(ret))
    152 self.fun_val = ret[0]
    153 if self.forward:

File ~/anaconda3/lib/python3.11/concurrent/futures/process.py:606, in _chain_from_iterable_of_lists(iterable)
    600 def _chain_from_iterable_of_lists(iterable):
    601     """
    602     Specialized implementation of itertools.chain.from_iterable.
    603     Each item in *iterable* should be a list.  This function is
    604     careful not to keep references to yielded objects.
    605     """
--> 606     for element in iterable:
    607         element.reverse()
    608         while element:

File ~/anaconda3/lib/python3.11/concurrent/futures/_base.py:619, in Executor.map.<locals>.result_iterator()
    616 while fs:
    617     # Careful not to keep a reference to the popped future
    618     if timeout is None:
--> 619         yield _result_or_cancel(fs.pop())
    620     else:
    621         yield _result_or_cancel(fs.pop(), end_time - time.monotonic())

File ~/anaconda3/lib/python3.11/concurrent/futures/_base.py:317, in _result_or_cancel(***failed resolving arguments***)
    315 try:
    316     try:
--> 317         return fut.result(timeout)
    318     finally:
    319         fut.cancel()

File ~/anaconda3/lib/python3.11/concurrent/futures/_base.py:456, in Future.result(self, timeout)
    454     raise CancelledError()
    455 elif self._state == FINISHED:
--> 456     return self.__get_result()
    457 else:
    458     raise TimeoutError()

File ~/anaconda3/lib/python3.11/concurrent/futures/_base.py:401, in Future.__get_result(self)
    399 if self._exception:
    400     try:
--> 401         raise self._exception
    402     finally:
    403         # Break a reference cycle with the exception in self._exception
    404         self = None

BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

**Comment by florafauna** [comment]
Please reopen the issue with a minimal reproducible example that work when using `minimize(method='L-BFGS-B')` but not with `minimize_parallel()`.
