### ISSUE TITLE
Support for constraints

### ISSUE THREAD

**Issue by ogencoglu** [florafauna/optimParallel-python#20]
Thanks for the work.

`scipy'`s L-BFGS-B supports constraints: https://docs.scipy.org/doc/scipy/reference/optimize.minimize-lbfgsb.html#optimize-minimize-lbfgsb

Do you plan to add such support?

**Comment by florafauna** [comment]
Short answer: no.

`minimize_parallel()` is only implemented for the method "L-BFGS-B", which supports `bounds`, but not `constraints`, see https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.fmin_l_bfgs_b.html#scipy.optimize.fmin_l_bfgs_b. Other optimization algorithms that support `constraints` may require a different parallelization approach. This is not currently planned as part of the project. 

Of course, I will evaluate PRs that offer parallel implementations of optimizers other than L-BFGS-B. Contributions are welcome.
