### ISSUE TITLE
hess_inv returned as array and not object

### ISSUE THREAD

**Issue by PS-OnGit** [florafauna/optimParallel-python#3]
I am using the minimize_parallel for a optimization of negative log likelihoods.

But for the continuation in my program I need the inv_hessian in the same way that it is returned from scipy.minimize, but it is returned as a multidimensional array.

is it possible to change this return Value in a future release?

kind regards

**Comment by florafauna** [comment]
The desired behaviour can be achieved by commenting out line 355 in `src/optimparallel.py`.

I will leave this issue open until it is fixed. (I am not sure yet, when I will find to do this.)

**Comment by PS-OnGit** [comment]
This fixes the output.

Thank you very much!!

**Comment by florafauna** [comment]
Problem is solved in version 0.1.2.
